name: 948moose
favicon: null
layout_spectrum: 0.49697
typography_spectrum: 0.19674
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#68330b'
    - '#241206'
    - '#9b7046'
    - '#e2b26a'
    - '#f6e1ac'
  brandStrength: 0.06724995421245694
  lightness: 0.46736178384162486
  saturation: 0.5
  rhythmicContrast: 0.4239282684866339
purpose: []
